apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-example
  namespace: metrics-example
  labels:
    monitoring: prometheus
spec:
  endpoints:
    - interval: 15s
      port: http
  namespaceSelector:
    matchNames:
      - metrics-example
  selector:
    matchLabels:
      monitoring: prometheus
