apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metrics-example
  namespace: metrics-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-example
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: topic_lag_external
          selector: # this is optional
            matchLabels:
              group_id: our_example_service
              topic_name: example-topic
        target:
          type: AverageValue
          averageValue: 1
