---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitor: "true"
  serviceMonitorSelector:
    matchLabels:
      monitoring: prometheus
  logLevel: info
  queryLogFile: /prometheus/query.log
